version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: laravel_db
    environment:
      POSTGRES_DB: students_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: jefferson@google.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - app_network

volumes:
  dbdata:

networks:
  app_network:
    driver: bridge
